<a href="https://colab.research.google.com/github/DaryaIgo/GB_Python_libraries_for_Data_Science/blob/lesson_1/Lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Вычисления с помощью Numpy

Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [ ]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [ ]:
a_centered = np.subtract(a.copy(), mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [ ]:
a_centered_sp = a_centered.T[0].dot(a_centered.T[1])
a_centered_sp

8.0

In [ ]:
N = a_centered.shape[0]
a_centered_sp_N = a_centered_sp / (N - 1)
a_centered_sp_N

2.0

Задание 4**
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. 
В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, 
поэтому полученная нами величина является несмещенной оценкой ковариации.
В этом задании проверьте получившееся число, 
вычислив ковариацию еще одним способом - с помощью функции np.cov. 
В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. 
В получившейся ковариационной матрице (массив Numpy размером 2x2) 
искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [ ]:
np.cov(a.T)[0, 1]

2.0

### Работа с данными в Pandas

Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. 
Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, 
в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 
 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [ ]:
import pandas as pd

In [ ]:
authors = pd.DataFrame({
    'author_id' : [1, 2, 3],
    'author_name' : ['Тургенев', 'Чехов', 'Островский']
})

In [ ]:
book = pd.DataFrame({
    'author_id' : [1, 1, 1, 2, 2, 3, 3],
    'book_title' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price' : [450, 300, 350, 500, 450, 370, 290]
})

Задание 2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [ ]:
authors_price = authors.merge(book, how = 'outer', on = 'author_id')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [ ]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price. 
В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, 
максимальная и средняя цена на книги этого автора.

In [ ]:
authors_stat = authors_price.groupby('author_name').agg({'price':['min', 'max', 'mean']})
authors_stat

price                 
              min  max        mean
author_name                       
Островский    290  370  330.000000
Тургенев      300  450  366.666667
Чехов         450  500  475.000000

In [ ]:
authors_stat = authors_stat.rename(columns={'min' : 'min_price', 'max' : 'max_price', 'mean': 'mean_price'})
authors_stat

price                      
            min_price max_price  mean_price
author_name                                
Островский        290       370  330.000000
Тургенев          300       450  366.666667
Чехов             450       500  475.000000